const GETMENUITEM = 'GETMENUITEM';
const ADDMENUITEMTOBILL = 'ADDMENUITEMTOBILL';
const REMOVEMENUITEMFROMBILL = 'REMOVEMENUITEMFROMBILL';
const RESETBILL = 'RESETBILL';

export default{
    GETMENUITEM,
    ADDMENUITEMTOBILL,
    REMOVEMENUITEMFROMBILL,
    RESETBILL
}