
const GETLISTNEWTIMEWORK = 'GETLISTNEWTIMEWORK';
const GETTIMEWORKLISTS = 'GETTIMEWORKLISTS';
const SEARCHTIMEWORK = 'SEARCHTIMEWORK';
const GETTIMEWORKS = 'GETTIMEWORKS';

export default {
    GETLISTNEWTIMEWORK,
    GETTIMEWORKLISTS,
    SEARCHTIMEWORK,
    GETTIMEWORKS
}